sonarcloud error

diff --git a/.github/workflows/sonarIssues.yml b/.github/workflows/sonarIssues.yml
--- a/.github/workflows/sonarIssues.yml
+++ b/.github/workflows/sonarIssues.yml
@@ -17,6 +17,19 @@ jobs:
         uses: SonarSource/sonarqube-scan-action@v5
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
+
+      - name: Check SonarQube Quality Gate
+        run: |
+            STATUS=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
+              "https://sonarcloud.io/web_api/api/qualitygates/project_status?projectKey=nithishpk_github-workflow-learning" \
+              | jq -r .projectStatus.status)
+      
+            echo "SonarQube Quality Gate Status: $STATUS"
+      
+            if [ "$STATUS" != "OK" ]; then
+              echo "Quality gate failed!"
+              exit 1
+            fi
       - name: discard secrets
         run: |
           echo "printing discard secrets"
